### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Vanessacruzortiz#1]
[Infografía de conceptos y funciones de una libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Vanessacruzortiz/files/14661739/Infografia.de.conceptos.y.funciones.de.una.libreria.pdf)

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica de evaluacion obtuviste el 20% 

** Puntos a mejorar, no repetir informacion, y agregar graficos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
